# Generated by Django 3.1.12 on 2022-07-25 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('monto_un', models.FloatField()),
                ('un', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_proyecto', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100, null=True)),
                ('trello', models.URLField(null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_entrega', models.DateField(null=True)),
                ('estado', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('total', models.FloatField()),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woody_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('monto_un', models.FloatField()),
                ('un', models.IntegerField()),
                ('total', models.FloatField()),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woody_app.project')),
            ],
        ),
    ]
